### ISSUE TITLE
有什么新的东西吗 大佬

### ISSUE THREAD

**Issue by sssssshf** [derronqi/yolov7-face#1]
有像 yolov5 --> yolov5face 那样de 新东西吗

**Comment by derronqi** [comment]
跟v7-pose一样，landmark有置信度了，修改了v7-pose里面关键点回归的bug

**Comment by sssssshf** [comment]
> 跟v7-pose一样，landmark有置信度了，修改了v7-pose里面关键点回归的bug

大佬的实验 同样的条件下  精度会超过yolo5face吗。好像现在论文都是召回率map，有测试误检率漏检率吗

**Comment by derronqi** [comment]
后面会陆续有测试数据出来

**Comment by BaofengZan** [comment]
> 跟v7-pose一样，landmark有置信度了，修改了v7-pose里面关键点回归的bug
具体有哪些bug，能说下么？
