### ISSUE TITLE
The effect of the test selfie picture is derived from which model？

### ISSUE THREAD

**Issue by YushengZhang** [derronqi/yolov7-face#11]
Hi！
I‘m testing the effect of yolov7-tiny-face.pt and I found that the inference effect of selfie image is different from what it is shown in the markdown, so I wonder the effect provided in markdown is derived from which model, thank you!

**Comment by derronqi** [comment]
yolov7-face

**Comment by YushengZhang** [comment]
> test size 2048

It works! Thank you!
