### ISSUE TITLE
yolov7-w6 and yolov7-w6+TTA weight refer to the same URL

### ISSUE THREAD

**Issue by kartikeyporwal** [derronqi/yolov7-face#14]
Weight file url of `yolov7-w6` and `yolov7-w6+TTA` refers to the same Google Drive URL in [`README.md`](https://github.com/derronqi/yolov7-face/blob/e37aee4336cae1afed4d676d930885223f4417ed/README.md)

**Comment by derronqi** [comment]
yes

**Comment by kartikeyporwal** [comment]
Thanks for confirming. I didn't know that TTA is about inferencing image at different scale, found [this](https://github.com/ultralytics/yolov5/issues/303) great tutorial from [`YOLOV5`](https://github.com/ultralytics/yolov5/) repo.

But, I think there is some bug that does not let proper scaling of the keypoints/landmarks coordinates when using TTA with/without image scaling by specifying the arguments `--augment --img 832` or `augment`. Some of the landmarks coordinates are not being scaled as per the image size and end up plotted at random places in the frame.
