### ISSUE TITLE
Anchor设置

### ISSUE THREAD

**Issue by maketo97** [derronqi/yolov7-face#2]
@derronqi 你好，大佬，想请教下，要如何根据关键点去设置yolov7-tiny-face.yaml的anchor呢？

**Comment by derronqi** [comment]
anchor是根据框生成的

**Comment by maketo97** [comment]
@derronqi 可以麻烦你解释下具体方法吗？大佬可以分享下你使用的pretrained yolov7-tiny模型吗？

**Comment by derronqi** [comment]
模型这俩天会放出来

**Comment by maketo97** [comment]
@derronqi 好的。感谢分享。如果脸部的关键点从5增加到20个的话，yolov7-tiny-face.yaml只需要改动(nkpt: 20)就可以了吗？

**Comment by derronqi** [comment]
目前还不可以
