### ISSUE TITLE
Preprocessing custom Dataset

### ISSUE THREAD

**Issue by BarakeelFanseuKamhoua** [derronqi/yolov7-face#22]
Hello,

Really great work.

Was wondering how to process a custom dataset in order to use this project. Since the label files provided has 20 columns instead of 15, I am wondering what each column stands for (I think the 1stis the class, and the next 4 are the normalized box values, but I can't figure out the rest especially as there are values >1 e.g., 2 in some columns).

A preprocessing file for a custom dataset or an explanation of the meaning of each of the 20 columns will be much appreciated.

God bless!

**Comment by BarakeelFanseuKamhoua** [comment]
Thanks so much for your good response.
1. Are the cx cy cw ch  kpt1_x kpt1_y ... same as in yolov3? 
2. Is the  visiable1 visiable2  ... only 0 for invisible and 2 for visible?

**Comment by derronqi** [comment]
yes

**Comment by BarakeelFanseuKamhoua** [comment]
Thanks for the clarity. Closing this issue now.

God bless.

**Comment by LuongDucLong** [comment]
@derronqi I have a question, which tool should I use for labeling both bounding boxes and keypoints in 1 line? I have an own dataset and I want to train on it.

**Comment by BarakeelFanseuKamhoua** [comment]
> @derronqi I have a question, which tool should I use for labeling both bounding boxes and key-points in 1 line? I have an own dataset and I want to train on it.

Hello,

I think you can use tools such as labelme, roboflow, and others (you may watch a demo on how to make them output yolo format, and then use a python script to modify the label files to the format mentioned by @derronqiI in his response to me i.e., inserting 0 or 2 at positions  8, 11, 14, 17,  and 20 (where 0 is keypoint invisible and 2 is visible) see picture below.  
![image](https://user-images.githubusercontent.com/106661928/203456410-58fdb1e6-7e56-47b1-846d-10232c0a8f9e.png)

Or if you want to use a pre-existing dataset such as FDDB or others you may use a python script to convert to the right label format mentioned above.

God bless!
