### ISSUE TITLE
wrong layer reference in lite models?

### ISSUE THREAD

**Issue by ucohen** [derronqi/yolov7-face#29]
https://github.com/derronqi/yolov7-face/blob/563481f4d4f74b4ae0e10a9422d85d7185712e12/cfg/yolov7-lite-s.yaml#L46

https://github.com/derronqi/yolov7-face/blob/563481f4d4f74b4ae0e10a9422d85d7185712e12/cfg/yolov7-lite-t.yaml#L46

should it reference layers: 15,18,21 ?

**Comment by derronqi** [comment]
yes, thanks
