### ISSUE TITLE
About IKeypoint head issue

### ISSUE THREAD

**Issue by cswwp** [derronqi/yolov7-face#37]
Hi, @derronqi Thank you for share so great project, and i have confused by this line 
'self.no_kpt = 3*self.nkpt ## number of outputs per anchor for keypoints'  in yolo.py file.

nkpt represent the number of face kpts, and everey kpt represent by (x, y), so no_kpt should equal to 2* nkpt, but why you write 3*self.nkpt. Do you mind explain it? Thank you 

class IKeypoint(nn.Module):
    stride = None  # strides computed during build
    export = False  # onnx export

    def __init__(self, nc=80, anchors=(), nkpt=5, ch=(), inplace=True, dw_conv_kpt=False):  # detection layer
        super(IKeypoint, self).__init__()
        self.nc = nc  # number of classes
        self.nkpt = nkpt
        self.dw_conv_kpt = dw_conv_kpt
        self.no_det=(nc + 5)  # number of outputs per anchor for box and class    x, y, w, h, confidence, class1 conf, class2 conf ......
        self.no_kpt = 3*self.nkpt ## number of outputs per anchor for keypoints
        self.no = self.no_det+self.no_kpt
        self.nl = len(anchors)  # number of detection layers
        self.na = len(anchors[0]) // 2  # number of anchors

**Comment by derronqi** [comment]
x, y, score
