### ISSUE TITLE
关于数据、标签目录放置问题

### ISSUE THREAD

**Issue by cswwp** [derronqi/yolov7-face#38]
我下载下来以后widerface 的目录如下图
![image](https://user-images.githubusercontent.com/11901683/219313235-550e9a65-1627-4b26-b5f2-d31c8efc8d46.png)

readme里边提供的label 目录为
![image](https://user-images.githubusercontent.com/11901683/219314004-e3092735-0177-484e-9d44-7fb5489cff24.png)
运行代码发现，根据img的文件名来构建对应的label 文件名和路径

![image](https://user-images.githubusercontent.com/11901683/219314329-f782d843-bf42-45b7-a920-548e594c02d7.png)

似乎需要手动将label 放置到对应的widerface的子文件夹下，或者修改代码，请问是这样吗？ 还是说我这边配置文件有问题，我的配置文件用的widerface.yaml

**Comment by cswwp** [comment]
我修改了 img2label_paths，目前能train起来了，我目前的数据目录🌲如下：
![image](https://user-images.githubusercontent.com/11901683/219325125-611ead15-f01c-474a-b0f8-af2326bb7de7.png)


def img2label_paths(img_paths):
    # Define label paths as a function of image paths
    sa, sb = os.sep + 'images' + os.sep, os.sep + 'labels' + os.sep  # /images/, /labels/ substrings
    label_fns = []
    for x in img_paths:
        fn = 'txt'.join(x.replace(sa, sb, 1).rsplit(x.split('.')[-1], 1)).split('/')
        label_fns.append(os.path.join('/'.join(fn[:-2]), fn[-1]))
    return label_fns
    # return ['txt'.join(x.replace(sa, sb, 1).rsplit(x.split('.')[-1], 1)) for x in img_paths]

**Comment by derronqi** [comment]
参考yolov5或者yolov7的数据集怎么弄的，都一样的
