### ISSUE TITLE
self.flip_index = [1, 0, 2, 4, 3] 这个设置是是什么意思啊

### ISSUE THREAD

**Issue by wuxiaolianggit** [derronqi/yolov7-face#39]
请问大佬,self.flip_index = [1, 0, 2, 4, 3] 这个设置是是什么意思啊？ @cansik @kartikeyporwal @derronqi @WallZFE @dsawll2

**Comment by derronqi** [comment]
左右flip，关键点映射用的

**Comment by wuxiaolianggit** [comment]
多谢大佬的解答啊 @derronqi

**Comment by retioa11** [comment]
可否具体解释一下啊？

**Comment by retioa11** [comment]
大佬可否具体解释一下？ 为啥要左右flip，怎么左右flip？

**Comment by retioa11** [comment]
大佬可否具体解释一下？ 为啥要左右flip，怎么左右flip？

**Comment by retioa11** [comment]
大佬可否具体解释一下？ 为啥要左右flip，怎么左右flip？ 如果检测车牌的4个关键点，label文件是下面这个样的，flip_index的值应该是啥？
![image](https://user-images.githubusercontent.com/81463532/230253433-ec12874b-e122-4b3b-bbe3-154750c676ce.png)
