### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0) occurred

### ISSUE THREAD

**Issue by HEY0000** [derronqi/yolov7-face#5]
Hello
I want to use my custom data.

but the error occurred. 

the data can train yolov5-face, but yolov7-face can't train...

I think "self.segments" seems to be cause.

Could you tell me how to solve? 

![Screenshot from 2022-10-24 09-58-48](https://user-images.githubusercontent.com/46856558/197428117-2b563d7f-ad4f-4d38-b134-9d76286277db.png)

**Comment by derronqi** [comment]
keypoint format: x1 y1 visible x2 y2 visible...

**Comment by HEY0000** [comment]
@derronqi 
Thanks for the reply

Can I write like this?


0(class) 0.446875 0.7076388888888889 0.4078125 0.5430555555555556(det) (keypoints) 0.43671875 0.7611111111111111 0.47265625 visible 0.8444444444444444 0.415625 visible 0.8416666666666667 0.43828125 visible 0.6138888888888889 0.3390625 visible 0.6027777777777777 visible

**Comment by HEY0000** [comment]
> 

Thanks for the reply

Can I write like this?

0(class) 0.446875 0.7076388888888889 0.4078125 0.5430555555555556(det) (keypoints) 0.43671875 0.7611111111111111 0.47265625 visible 0.8444444444444444 0.415625 visible 0.8416666666666667 0.43828125 visible 0.6138888888888889 0.3390625 visible 0.6027777777777777 visible

**Comment by derronqi** [comment]
0 0.0098 0.2440 0.0195 0.0356 0.0029 0.2361 2.0000 0.0098 0.2347 2.0000 0.0098 0.2461 2.0000 0.0078 0.2532 2.0000 0.0137 0.2518 2.0000
0 0.3203 0.1935 0.0605 0.1206 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000

**Comment by xellDart** [comment]
> 0 0.0098 0.2440 0.0195 0.0356 0.0029 0.2361 2.0000 0.0098 0.2347 2.0000 0.0098 0.2461 2.0000 0.0078 0.2532 2.0000 0.0137 0.2518 2.0000 0 0.3203 0.1935 0.0605 0.1206 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000

Hi, I already followed your changes, I use 2 for visible point, I use kpt-label for 4 keypoints, I have an error:

```
t[:, 6+2*kpt: 6+2*(kpt+1)][t[:,6+2*kpt: 6+2*(kpt+1)] !=0] -= gij[t[:,6+2*kpt: 6+2*(kpt+1)] !=0]
IndexError: The shape of the mask [0, 1] at index 1 does not match the shape of the indexed tensor [0, 2] at index 1
```
But I don't understand what causes this, could you help me?
