### ISSUE TITLE
utils/loss.py似乎不支持多分类问题

### ISSUE THREAD

**Issue by Faccococo** [derronqi/yolov7-face#57]
您好！我注意到在utils/loss.py的170行附近有这样一处表达：pkpt_score = ps[:, 8::3]
您似乎没有考虑多分类的情况？当分类数量大于1时，关键点的置信度应该并不是从8，而是从7+num_class处开始。

**Comment by XhHello** [comment]
> 您好！我注意到在utils/loss.py的170行附近有这样一处表达：pkpt_score = ps[:, 8::3] 您似乎没有考虑多分类的情况？当分类数量大于1时，关键点的置信度应该并不是从8，而是从7+num_class处开始。

请问为啥要从8改为7+num_calss呢

**Comment by CabbageWust** [comment]
> 您好！我注意到在utils/loss.py的170行附近有这样一处表达：pkpt_score = ps[:, 8::3] 您似乎没有考虑多分类的情况？当分类数量大于1时，关键点的置信度应该并不是从8，而是从7+num_class处开始。

那“pkpt_x = ps[:, 6::3] * 2. - 0.5”  和 “pkpt_y = ps[:, 7::3] * 2. - 0.5” 这两句是不是都要改，请问下您训练了多分类了吗？

**Comment by Faccococo** [comment]
> 看起来是的。我还没能走完整个训练流程，看起来像是在生成混淆矩阵是出错了

**Comment by Faccococo** [comment]
> > 您好！我注意到在utils/loss.py的170行附近有这样一处表达：pkpt_score = ps[:, 8::3] 您似乎没有考虑多分类的情况？当分类数量大于1时，关键点的置信度应该并不是从8，而是从7+num_class处开始。
> 
> 那“pkpt_x = ps[:, 6::3] * 2. - 0.5” 和 “pkpt_y = ps[:, 7::3] * 2. - 0.5” 这两句是不是都要改，请问下您训练了多分类了吗？

看起来是的。我还没能走完整个训练流程，看起来像是在生成混淆矩阵是出错了

**Comment by faccoco** [comment]
由于太久没有回复，我决定关闭这个issue。
