### ISSUE TITLE
Training weight files for yolov7-lite-e and yolov7-tiny-leak

### ISSUE THREAD

**Issue by maketo97** [derronqi/yolov7-face#9]
@derronqi May I get the download link of the training weight file for those two model files (yolov7-lite-e and yolov7-tiny-leak)?

**Comment by derronqi** [comment]
![image](https://user-images.githubusercontent.com/34156011/197957482-abaa8ace-d8d8-423c-a282-4ff57b8f0148.png)

**Comment by maketo97** [comment]
@derronqi Sorry for my typo, I mean the pretrained model for yolov7-lite-e and yolov7-tiny-leak.
